In [24]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.feature_selection import RFE
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn import preprocessing
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
le = preprocessing.LabelEncoder()
from sklearn.model_selection import train_test_split

from imblearn.under_sampling import RandomUnderSampler
from imblearn.pipeline import Pipeline
from imblearn.over_sampling import SMOTE

In [25]:
from fast_ml.model_development import train_valid_test_split

raw_data= pd.read_csv("reduced_data.csv")

# Splitting the data into Training, validation and test sets
X_train, y_train, X_valid, y_valid, X_test, y_test = train_valid_test_split(data, target = "churn_probability",
train_size=0.7, valid_size=0.2, test_size=0.1, random_state=5)

In [26]:
X_train= X_train.loc[:, ~X_train.columns.isin(['id', 'churn_probability', 'date_of_last_rech'])]
X_valid= X_valid.loc[:, ~X_valid.columns.isin(['id', 'churn_probability', 'date_of_last_rech'])]
X_test= X_test.loc[:, ~X_test.columns.isin(['id', 'churn_probability', 'date_of_last_rech'])]

In [27]:
clf= DecisionTreeClassifier(max_depth= 30)
clf.fit(X_train, y_train)

DecisionTreeClassifier(max_depth=30)

In [39]:
confusion_matrix(y_train, clf.predict(X_train))

array([[127976,     72],
       [  1091,   9864]], dtype=int64)

In [40]:
confusion_matrix(y_valid, clf.predict(X_valid))

array([[34183,  2371],
       [ 2427,   734]], dtype=int64)

In [41]:
confusion_matrix(y_test, clf.predict(X_test))

array([[17113,  1123],
       [ 1238,   384]], dtype=int64)

In [58]:
for i in range(5, 51, 5):
    clf= DecisionTreeClassifier(max_depth= i, min_samples_split= 50)
    clf.fit(X_train, y_train)
    print("*"*100)
    print(i)
    print("Train")
    print(accuracy_score(y_train, clf.predict(X_train)))
    print(confusion_matrix(y_train, clf.predict(X_train)))
    print("Validation")
    print(accuracy_score(y_valid, clf.predict(X_valid)))
    print(confusion_matrix(y_valid, clf.predict(X_valid)))
    print("Test")
    print(accuracy_score(y_test, clf.predict(X_test)))
    print(confusion_matrix(y_test, clf.predict(X_test)))

****************************************************************************************************
5
Train
0.9247498255433336
[[127537    511]
 [  9949   1006]]
Validation
0.922875487850938
[[36398   156]
 [ 2907   254]]
Test
0.9220968879041193
[[18157    79]
 [ 1468   154]]
****************************************************************************************************
10
Train
0.9278720603152449
[[127297    751]
 [  9275   1680]]
Validation
0.9207604179780939
[[36221   333]
 [ 2814   347]]
Test
0.9202840165172727
[[18082   154]
 [ 1429   193]]
****************************************************************************************************
15
Train
0.9343467407178262
[[126798   1250]
 [  7876   3079]]
Validation
0.9132317764068991
[[35786   768]
 [ 2678   483]]
Test
0.9135864638936448
[[17882   354]
 [ 1362   260]]
****************************************************************************************************
20
Train
0.9387423293022453
[[126633   1415]
 [  7100   3855]

In [55]:
for i in range(5, 51, 5):
    clf= DecisionTreeClassifier(max_depth= i)
    clf.fit(X_train, y_train)
    print("*"*100)
    print(i)
    print("Train")
    print(accuracy_score(y_train, clf.predict(X_train)))
    print(confusion_matrix(y_train, clf.predict(X_train)))
    print("Validation")
    print(accuracy_score(y_valid, clf.predict(X_valid)))
    print(confusion_matrix(y_valid, clf.predict(X_valid)))
    print("Test")
    print(accuracy_score(y_test, clf.predict(X_test)))
    print(confusion_matrix(y_test, clf.predict(X_test)))

****************************************************************************************************
5
Train
0.9247498255433336
[[127537    511]
 [  9949   1006]]
Validation
0.922875487850938
[[36398   156]
 [ 2907   254]]
Test
0.9220968879041193
[[18157    79]
 [ 1468   154]]
****************************************************************************************************
10
Train
0.9305554556376481
[[127376    672]
 [  8981   1974]]
Validation
0.9207352385748457
[[36202   352]
 [ 2796   365]]
Test
0.9204854466713667
[[18069   167]
 [ 1412   210]]
****************************************************************************************************
15
Train
0.9480946454393071
[[127474    574]
 [  6641   4314]]
Validation
0.9096059423391666
[[35627   927]
 [ 2663   498]]
Test
0.9101621512740458
[[17805   431]
 [ 1353   269]]
****************************************************************************************************
20
Train
0.9691805212837133
[[127735    313]
 [  3971   6984]

In [61]:
for i in range(1, 15):
    clf= DecisionTreeClassifier(max_depth= i)
    clf.fit(X_train, y_train)
    print("*"*100)
    print(i)
    print("Train")
    print(accuracy_score(y_train, clf.predict(X_train)))
    print(confusion_matrix(y_train, clf.predict(X_train)))
    print("Validation")
    print(accuracy_score(y_valid, clf.predict(X_valid)))
    print(confusion_matrix(y_valid, clf.predict(X_valid)))
    print("Test")
    print(accuracy_score(y_test, clf.predict(X_test)))
    print(confusion_matrix(y_test, clf.predict(X_test)))

****************************************************************************************************
1
Train
0.9211887513219139
[[128048      0]
 [ 10955      0]]
Validation
0.9204079063326199
[[36554     0]
 [ 3161     0]]
Test
0.9183200725148555
[[18236     0]
 [ 1622     0]]
****************************************************************************************************
2
Train
0.9222103120076545
[[127038   1010]
 [  9803   1152]]
Validation
0.9206345209618532
[[36254   300]
 [ 2852   309]]
Test
0.9208379494410314
[[18104   132]
 [ 1440   182]]
****************************************************************************************************
3
Train
0.9238577584656447
[[127378    670]
 [  9914   1041]]
Validation
0.9220697469469974
[[36354   200]
 [ 2895   266]]
Test
0.9220968879041193
[[18148    88]
 [ 1459   163]]
****************************************************************************************************
4
Train
0.9245915555779372
[[127517    531]
 [  9951   1004]]


## Adaboost

In [11]:
from sklearn.ensemble import AdaBoostClassifier

In [76]:
for i in range(1, 5):
    decision_clf= DecisionTreeClassifier(max_depth= i)
    clf = AdaBoostClassifier(decision_clf, n_estimators=50, random_state=0)
    clf.fit(X_train, y_train)
    print("*"*100)
    print(i)
    print("Train")
    print(accuracy_score(y_train, clf.predict(X_train)))
    print(confusion_matrix(y_train, clf.predict(X_train)))
    print("Validation")
    print(accuracy_score(y_valid, clf.predict(X_valid)))
    print(confusion_matrix(y_valid, clf.predict(X_valid)))
    print("Test")
    print(accuracy_score(y_test, clf.predict(X_test)))
    print(confusion_matrix(y_test, clf.predict(X_test)))

****************************************************************************************************
1
Train
0.9170377617749257
[[126656   1392]
 [ 10140    815]]
Validation
0.9171849427168576
[[36184   370]
 [ 2919   242]]
Test
0.9157518380501561
[[18044   192]
 [ 1481   141]]
****************************************************************************************************
2
Train
0.9241383279497565
[[127178    870]
 [  9675   1280]]
Validation
0.9219942087372529
[[36266   288]
 [ 2810   351]]
Test
0.92139188236479
[[18101   135]
 [ 1426   196]]
****************************************************************************************************
3
Train
0.924800184168687
[[127080    968]
 [  9485   1470]]
Validation
0.9210373914138235
[[36225   329]
 [ 2807   354]]
Test
0.9217947426729781
[[18090   146]
 [ 1407   215]]
****************************************************************************************************
4
Train
0.9262461961252635
[[126733   1315]
 [  8937   2018]]
Val

In [80]:
for i in range(2, 6):
    decision_clf= DecisionTreeClassifier(max_depth= i)
    clf = AdaBoostClassifier(decision_clf, n_estimators=100, random_state=0, learning_rate= 0.5)
    clf.fit(X_train, y_train)
    print("*"*100)
    print(i)
    print("Train")
    print(accuracy_score(y_train, clf.predict(X_train)))
    print(confusion_matrix(y_train, clf.predict(X_train)))
    print("Validation")
    print(accuracy_score(y_valid, clf.predict(X_valid)))
    print(confusion_matrix(y_valid, clf.predict(X_valid)))
    print("Test")
    print(accuracy_score(y_test, clf.predict(X_test)))
    print(confusion_matrix(y_test, clf.predict(X_test)))

****************************************************************************************************
2
Train
0.9243469565405064
[[127435    613]
 [  9903   1052]]
Validation
0.921843132317764
[[36349   205]
 [ 2899   262]]
Test
0.9217947426729781
[[18132   104]
 [ 1449   173]]
****************************************************************************************************
3
Train
0.9258864916584534
[[127285    763]
 [  9539   1416]]
Validation
0.9222711821729825
[[36294   260]
 [ 2827   334]]
Test
0.9226004632893544
[[18120   116]
 [ 1421   201]]
****************************************************************************************************
4
Train
0.9285339165341755
[[127208    840]
 [  9094   1861]]
Validation
0.9223970791892232
[[36249   305]
 [ 2777   384]]
Test
0.9220968879041193
[[18089   147]
 [ 1400   222]]
****************************************************************************************************
5
Train
0.9337640194815939
[[127183    865]
 [  8342   2613]]
V

In [83]:
for i in range(2, 6):
    decision_clf= DecisionTreeClassifier(max_depth= i, min_samples_split= 100)
    clf = AdaBoostClassifier(decision_clf, n_estimators=100, random_state=0, learning_rate= 0.5)
    clf.fit(X_train, y_train)
    print("*"*100)
    print(i)
    print("Train")
    print(accuracy_score(y_train, clf.predict(X_train)))
    print(confusion_matrix(y_train, clf.predict(X_train)))
    print("Validation")
    print(accuracy_score(y_valid, clf.predict(X_valid)))
    print(confusion_matrix(y_valid, clf.predict(X_valid)))
    print("Test")
    print(accuracy_score(y_test, clf.predict(X_test)))
    print(confusion_matrix(y_test, clf.predict(X_test)))

****************************************************************************************************
2
Train
0.9243253742724977
[[127440    608]
 [  9911   1044]]
Validation
0.9221452851567418
[[36353   201]
 [ 2891   270]]
Test
0.9222983180582133
[[18139    97]
 [ 1446   176]]
****************************************************************************************************
3
Train
0.9257138335143846
[[127305    743]
 [  9583   1372]]
Validation
0.9222460027697343
[[36291   263]
 [ 2825   336]]
Test
0.9226004632893544
[[18122   114]
 [ 1423   199]]
****************************************************************************************************
4
Train
0.927944001208607
[[127178    870]
 [  9146   1809]]
Validation
0.9223215409794788
[[36262   292]
 [ 2793   368]]
Test
0.9222479605196898
[[18086   150]
 [ 1394   228]]
****************************************************************************************************
5
Train
0.9315914045020611
[[127141    907]
 [  8602   2353]]
V

In [84]:
for i in range(2, 6):
    decision_clf= DecisionTreeClassifier(max_depth= i, min_samples_split= 100, splitter= 'random')
    clf = AdaBoostClassifier(decision_clf, n_estimators=100, random_state=0, learning_rate= 0.5)
    clf.fit(X_train, y_train)
    print("*"*100)
    print(i)
    print("Train")
    print(accuracy_score(y_train, clf.predict(X_train)))
    print(confusion_matrix(y_train, clf.predict(X_train)))
    print("Validation")
    print(accuracy_score(y_valid, clf.predict(X_valid)))
    print(confusion_matrix(y_valid, clf.predict(X_valid)))
    print("Test")
    print(accuracy_score(y_test, clf.predict(X_test)))
    print(confusion_matrix(y_test, clf.predict(X_test)))

****************************************************************************************************
2
Train
0.9219297425235427
[[127782    266]
 [ 10586    369]]
Validation
0.9208611355910865
[[36474    80]
 [ 3063    98]]
Test
0.9188236479000906
[[18193    43]
 [ 1569    53]]
****************************************************************************************************
3
Train
0.9240591929670583
[[127405    643]
 [  9913   1042]]
Validation
0.921843132317764
[[36343   211]
 [ 2893   268]]
Test
0.921291167287743
[[18139    97]
 [ 1466   156]]
****************************************************************************************************
4
Train
0.9250232009381093
[[127254    794]
 [  9628   1327]]
Validation
0.9222963615762306
[[36304   250]
 [ 2836   325]]
Test
0.9218451002115017
[[18110   126]
 [ 1426   196]]
****************************************************************************************************
5
Train
0.9262965547506169
[[127318    730]
 [  9515   1440]]
Va

In [87]:
for i in range(2, 6):
    decision_clf= DecisionTreeClassifier(max_depth= i, splitter= 'random')
    clf = AdaBoostClassifier(decision_clf, n_estimators=200, random_state=0, learning_rate= 0.5)
    clf.fit(X_train, y_train)
    print("*"*100)
    print(i)
    print("Train")
    print(accuracy_score(y_train, clf.predict(X_train)))
    print(confusion_matrix(y_train, clf.predict(X_train)))
    print("Validation")
    print(accuracy_score(y_valid, clf.predict(X_valid)))
    print(confusion_matrix(y_valid, clf.predict(X_valid)))
    print("Test")
    print(accuracy_score(y_test, clf.predict(X_test)))
    print(confusion_matrix(y_test, clf.predict(X_test)))

****************************************************************************************************
2
Train
0.9233182017654296
[[127498    550]
 [ 10109    846]]
Validation
0.921465441269042
[[36372   182]
 [ 2937   224]]
Test
0.9208883069795548
[[18164    72]
 [ 1499   123]]
****************************************************************************************************
3
Train
0.9251670827248333
[[127360    688]
 [  9714   1241]]
Validation
0.9213395442528012
[[36310   244]
 [ 2880   281]]
Test
0.921089737133649
[[18121   115]
 [ 1452   170]]
****************************************************************************************************
4
Train
0.9272389804536593
[[127269    779]
 [  9335   1620]]
Validation
0.9203827269293717
[[36231   323]
 [ 2839   322]]
Test
0.9211400946721724
[[18091   145]
 [ 1421   201]]
****************************************************************************************************
5
Train
0.9311022064271994
[[127225    823]
 [  8754   2201]]
Va

## Load imbalance

In [19]:
from collections import Counter

counter = Counter(y_train)
counter
smote_oversample = SMOTE(sampling_strategy=0.5)
#random_undersample = RandomUnderSampler(sampling_strategy=0.9)
#steps = [('o', smote_oversample), ('u', random_undersample)]
#pipeline_sample = Pipeline(steps=steps)
#X3, y3 = pipeline_sample.fit_resample(X_train2,y_train2)
X3, y3 = smote_oversample.fit_resample(X_train,y_train)
counter = Counter(y3)
counter
X_train5, X_test5, y_train5, y_test5 = train_test_split(X3,y3, test_size=0.2, train_size=0.8, random_state=7)

In [13]:
for i in range(2, 6):
    decision_clf= DecisionTreeClassifier(max_depth= i)
    clf = AdaBoostClassifier(decision_clf, n_estimators=100, random_state=0, learning_rate= 0.5)
    clf.fit(X_train5, y_train5)
    print("*"*100)
    print(i)
    print("Train")
    print(accuracy_score(y_train5, clf.predict(X_train5)))
    print(confusion_matrix(y_train5, clf.predict(X_train5)))
#     print("Validation")
#     print(accuracy_score(y_valid5, clf.predict(X_valid5)))
#     print(confusion_matrix(y_valid5, clf.predict(X_valid)))
    print("Test")
    print(accuracy_score(y_test5, clf.predict(X_test5)))
    print(confusion_matrix(y_test5, clf.predict(X_test5)))
    print("-"*100)
    print(i)
    print("True Train")
    print(accuracy_score(y_train, clf.predict(X_train)))
    print(confusion_matrix(y_train, clf.predict(X_train)))
    print("True Validation")
    print(accuracy_score(y_valid, clf.predict(X_valid)))
    print(confusion_matrix(y_valid, clf.predict(X_valid)))
    print("True Test")
    print(accuracy_score(y_test, clf.predict(X_test)))
    print(confusion_matrix(y_test, clf.predict(X_test)))

****************************************************************************************************
2
Train
0.8811248429944617
[[95103  7402]
 [10864 40288]]
Test
0.8771833919042041
[[23658  1885]
 [ 2833 10039]]
----------------------------------------------------------------------------------------------------
2
True Train
0.8819090235462544
[[118761   9287]
 [  7128   3827]]
True Validation
0.8817323429434722
[[33907  2647]
 [ 2050  1111]]
True Test
0.8791922650820828
[[16889  1347]
 [ 1052   570]]
****************************************************************************************************
3
Train
0.8968481748309547
[[96235  6270]
 [ 9580 41572]]
Test
0.8913965898737473
[[23882  1661]
 [ 2511 10361]]
----------------------------------------------------------------------------------------------------
3
True Train
0.8911030697179197
[[120117   7931]
 [  7206   3749]]
True Validation
0.888203449578245
[[34230  2324]
 [ 2116  1045]]
True Test
0.8875012589384631
[[17080  1156]
 

In [17]:
for i in range(2, 5):
    decision_clf= DecisionTreeClassifier(max_depth= i)
    clf = AdaBoostClassifier(decision_clf, n_estimators=50, random_state=0, learning_rate= 1)
    clf.fit(X_train5, y_train5)
    print("*"*100)
    print(i)
    print("Train")
    print(accuracy_score(y_train5, clf.predict(X_train5)))
    print(confusion_matrix(y_train5, clf.predict(X_train5)))
#     print("Validation")
#     print(accuracy_score(y_valid5, clf.predict(X_valid5)))
#     print(confusion_matrix(y_valid5, clf.predict(X_valid)))
    print("Test")
    print(accuracy_score(y_test5, clf.predict(X_test5)))
    print(confusion_matrix(y_test5, clf.predict(X_test5)))
    print("-"*100)
    print(i)
    print("True Train")
    print(accuracy_score(y_train, clf.predict(X_train)))
    print(confusion_matrix(y_train, clf.predict(X_train)))
    print("True Validation")
    print(accuracy_score(y_valid, clf.predict(X_valid)))
    print(confusion_matrix(y_valid, clf.predict(X_valid)))
    print("True Test")
    print(accuracy_score(y_test, clf.predict(X_test)))
    print(confusion_matrix(y_test, clf.predict(X_test)))

****************************************************************************************************
2
Train
0.8713368086061813
[[94006  8499]
 [11271 39881]]
Test
0.8671612651308083
[[23384  2159]
 [ 2944  9928]]
----------------------------------------------------------------------------------------------------
2
True Train
0.8723049142824255
[[117390  10658]
 [  7092   3863]]
True Validation
0.8718620168702002
[[33522  3032]
 [ 2057  1104]]
True Test
0.8708832712257025
[[16710  1526]
 [ 1038   584]]
****************************************************************************************************
3
Train
0.8864679122981706
[[94985  7520]
 [ 9925 41227]]
Test
0.8799166992060393
[[23572  1971]
 [ 2642 10230]]
----------------------------------------------------------------------------------------------------
3
True Train
0.8805493406617123
[[118557   9491]
 [  7113   3842]]
True Validation
0.8799949641193504
[[33891  2663]
 [ 2103  1058]]
True Test
0.8770268909255715
[[16858  1378]


In [21]:
for i in range(1, 5):
    decision_clf= DecisionTreeClassifier(max_depth= i)
    clf = AdaBoostClassifier(decision_clf, n_estimators=100, random_state=0, learning_rate= 1)
    clf.fit(X_train5, y_train5)
    print("*"*100)
    print(i)
    print("Train")
    print(accuracy_score(y_train5, clf.predict(X_train5)))
    print(confusion_matrix(y_train5, clf.predict(X_train5)))
#     print("Validation")
#     print(accuracy_score(y_valid5, clf.predict(X_valid5)))
#     print(confusion_matrix(y_valid5, clf.predict(X_valid)))
    print("Test")
    print(accuracy_score(y_test5, clf.predict(X_test5)))
    print(confusion_matrix(y_test5, clf.predict(X_test5)))
    print("-"*100)
    print(i)
    print("True Train")
    print(accuracy_score(y_train, clf.predict(X_train)))
    print(confusion_matrix(y_train, clf.predict(X_train)))
    print("True Validation")
    print(accuracy_score(y_valid, clf.predict(X_valid)))
    print(confusion_matrix(y_valid, clf.predict(X_valid)))
    print("True Test")
    print(accuracy_score(y_test, clf.predict(X_test)))
    print(confusion_matrix(y_test, clf.predict(X_test)))

****************************************************************************************************
1
Train
0.8663982102908278
[[98461  4023]
 [12400  8041]]
Test
0.86300924118183
[[24549  1015]
 [ 3195  1973]]
----------------------------------------------------------------------------------------------------
1
True Train
0.9009949425551966
[[123010   5038]
 [  8724   2231]]
True Validation
0.9006672541860757
[[35109  1445]
 [ 2500   661]]
True Test
0.9003424312619599
[[17521   715]
 [ 1264   358]]
****************************************************************************************************
2
Train
0.8936424649176327
[[98941  3543]
 [ 9531 10910]]
Test
0.8895939086294417
[[24624   940]
 [ 2453  2715]]
----------------------------------------------------------------------------------------------------
2
True Train
0.9083185254994497
[[123565   4483]
 [  8261   2694]]
True Validation
0.9059801082714339
[[35251  1303]
 [ 2431   730]]
True Test
0.9038674589586061
[[17554   682]
 [

KeyboardInterrupt: 

In [26]:
for i in range(2, 3):
    decision_clf= DecisionTreeClassifier(max_depth= i, splitter="random")
    clf = AdaBoostClassifier(decision_clf, n_estimators=200, random_state=0, learning_rate= 0.5)
    clf.fit(X_train5, y_train5)
    print("*"*100)
    print(i)
    print("Train")
    print(accuracy_score(y_train5, clf.predict(X_train5)))
    print(confusion_matrix(y_train5, clf.predict(X_train5)))
#     print("Validation")
#     print(accuracy_score(y_valid5, clf.predict(X_valid5)))
#     print(confusion_matrix(y_valid5, clf.predict(X_valid)))
    print("Test")
    print(accuracy_score(y_test5, clf.predict(X_test5)))
    print(confusion_matrix(y_test5, clf.predict(X_test5)))
    print("-"*100)
    print(i)
    print("True Train")
    print(accuracy_score(y_train, clf.predict(X_train)))
    print(confusion_matrix(y_train, clf.predict(X_train)))
    print("True Validation")
    print(accuracy_score(y_valid, clf.predict(X_valid)))
    print(confusion_matrix(y_valid, clf.predict(X_valid)))
    print("True Test")
    print(accuracy_score(y_test, clf.predict(X_test)))
    print(confusion_matrix(y_test, clf.predict(X_test)))

****************************************************************************************************
2
Train
0.8226131852398204
[[94339  8075]
 [16456 19421]]
Test
0.8202354438434617
[[23589  2045]
 [ 4170  4769]]
----------------------------------------------------------------------------------------------------
2
True Train
0.8783695315928434
[[117928  10120]
 [  6787   4168]]
True Validation
0.8764446682613622
[[33610  2944]
 [ 1963  1198]]
True Test
0.8750125893846309
[[16768  1468]
 [ 1014   608]]


In [28]:
import lightgbm as lgb

clf= lgb.LGBMClassifier(n_estimators= 154, num_leaves= 40, min_child_samples= 22, learning_rate= 0.04592957118721939, colsample_bytree= 0.6733735675646831, reg_alpha= 0.0009765625, reg_lambda= 18.492718255154934)

In [31]:
clf.fit(X_train, y_train)

LGBMClassifier(colsample_bytree=0.6733735675646831,
               learning_rate=0.04592957118721939, min_child_samples=22,
               n_estimators=154, num_leaves=40, reg_alpha=0.0009765625,
               reg_lambda=18.492718255154934)

In [32]:

print("-"*100)
print()
print("True Train")
print(accuracy_score(y_train, clf.predict(X_train)))
print(confusion_matrix(y_train, clf.predict(X_train)))
print("True Validation")
print(accuracy_score(y_valid, clf.predict(X_valid)))
print(confusion_matrix(y_valid, clf.predict(X_valid)))
print("True Test")
print(accuracy_score(y_test, clf.predict(X_test)))
print(confusion_matrix(y_test, clf.predict(X_test)))

----------------------------------------------------------------------------------------------------

True Train
0.9260951202492033
[[127403    645]
 [  9628   1327]]
True Validation
0.9236308699483822
[[36352   202]
 [ 2831   330]]
True Test
0.9230033235975426
[[18136   100]
 [ 1429   193]]


In [33]:
from sklearn.neighbors import KNeighborsClassifier

In [37]:
neigh = KNeighborsClassifier(n_neighbors=1)
neigh.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=1)

In [39]:
print("-"*100)
print()
print("True Train")
#y_pred= neigh.predict(X_train)
#print(accuracy_score(y_train, y_pred))
#print(confusion_matrix(y_train, y_pred))
print("True Validation")
y_pred= neigh.predict(X_valid)
print(accuracy_score(y_valid, y_pred))
print(confusion_matrix(y_valid, y_pred))
print("True Test")
print(accuracy_score(y_test, neigh.predict(X_test)))
print(confusion_matrix(y_test, neigh.predict(X_test)))

----------------------------------------------------------------------------------------------------

True Train
True Validation
0.8758403625834068
[[34128  2426]
 [ 2505   656]]
True Test
0.8760197401551012
[[17049  1187]
 [ 1275   347]]
