In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.feature_selection import RFE
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn import preprocessing
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
le = preprocessing.LabelEncoder()
from sklearn.model_selection import train_test_split

from imblearn.under_sampling import RandomUnderSampler
from imblearn.pipeline import Pipeline
from imblearn.over_sampling import SMOTE

In [23]:
from fast_ml.model_development import train_valid_test_split

raw_data= pd.read_csv("train.csv")
data= raw_data.loc[:, ~raw_data.columns.isin(cols)]
data= data.dropna()

# Splitting the data into Training, validation and test sets
X_train, y_train, X_valid, y_valid, X_test, y_test = train_valid_test_split(data, target = "churn_probability",
train_size=0.7, valid_size=0.2, test_size=0.1, random_state=5)

In [22]:
cols =["circle_id","loc_og_t2o_mou","std_og_t2o_mou","loc_ic_t2o_mou","std_og_t2c_mou_6","std_og_t2c_mou_7","std_og_t2c_mou_8","std_ic_t2o_mou_6","std_ic_t2o_mou_7","std_ic_t2o_mou_8",
      "fb_user_6","fb_user_7","fb_user_8","night_pck_user_6","night_pck_user_7","night_pck_user_8","arpu_3g_6","arpu_3g_7","arpu_3g_8","arpu_2g_6","arpu_2g_7","arpu_2g_8",
      "av_rech_amt_data_8","av_rech_amt_data_7","av_rech_amt_data_6","count_rech_3g_8","count_rech_3g_7","count_rech_3g_6","count_rech_2g_8","count_rech_2g_7","count_rech_2g_6",
      "max_rech_data_8","max_rech_data_7","max_rech_data_6","total_rech_data_8","total_rech_data_7","total_rech_data_6","date_of_last_rech_data_8","date_of_last_rech_data_7","date_of_last_rech_data_6",
      "last_date_of_month_6", "last_date_of_month_7", "last_date_of_month_8", "id", "date_of_last_rech_6", "date_of_last_rech_7", "date_of_last_rech_8"]

columns_to_use= ['total_ic_mou_8', 'vol_2g_mb_8', 'arpu_8', 'roam_og_mou_8',
       'last_day_rch_amt_8', 'std_og_mou_7', 'loc_ic_t2m_mou_8',
       'total_ic_mou_6', 'arpu_7', 'aon', 'total_og_mou_8',
       'total_rech_amt_8', 'vol_3g_mb_8', 'total_rech_num_8',
       'loc_ic_mou_8', 'total_rech_num_7', 'total_ic_mou_7',
       'roam_og_mou_7', 'loc_ic_mou_7', 'roam_ic_mou_8', 'std_ic_mou_7',
       'aug_vbc_3g', 'total_og_mou_6', 'loc_og_t2f_mou_8',
       'max_rech_amt_8', 'max_rech_amt_6', 'loc_ic_t2f_mou_6',
       'loc_ic_mou_6', 'last_day_rch_amt_7', 'isd_og_mou_6',
       'loc_og_t2f_mou_6', 'loc_og_mou_7', 'jul_vbc_3g', 'std_ic_mou_6',
       'loc_og_t2f_mou_7']

In [24]:
X_train= X_train.loc[:, ~X_train.columns.isin(["churn_probability"])]
X_valid= X_valid.loc[:, ~X_valid.columns.isin(["churn_probability"])]
X_test= X_test.loc[:, ~X_test.columns.isin(["churn_probability"])]

In [25]:
X_train.shape

(44689, 124)

In [15]:
X_train= X_train.dropna()

In [27]:
clf= DecisionTreeClassifier(max_depth= 30)
clf.fit(X_train, y_train)

DecisionTreeClassifier(max_depth=30)

In [39]:
confusion_matrix(y_train, clf.predict(X_train))

array([[127976,     72],
       [  1091,   9864]], dtype=int64)

In [40]:
confusion_matrix(y_valid, clf.predict(X_valid))

array([[34183,  2371],
       [ 2427,   734]], dtype=int64)

In [41]:
confusion_matrix(y_test, clf.predict(X_test))

array([[17113,  1123],
       [ 1238,   384]], dtype=int64)

In [58]:
for i in range(5, 51, 5):
    clf= DecisionTreeClassifier(max_depth= i, min_samples_split= 50)
    clf.fit(X_train, y_train)
    print("*"*100)
    print(i)
    print("Train")
    print(accuracy_score(y_train, clf.predict(X_train)))
    print(confusion_matrix(y_train, clf.predict(X_train)))
    print("Validation")
    print(accuracy_score(y_valid, clf.predict(X_valid)))
    print(confusion_matrix(y_valid, clf.predict(X_valid)))
    print("Test")
    print(accuracy_score(y_test, clf.predict(X_test)))
    print(confusion_matrix(y_test, clf.predict(X_test)))

****************************************************************************************************
5
Train
0.9247498255433336
[[127537    511]
 [  9949   1006]]
Validation
0.922875487850938
[[36398   156]
 [ 2907   254]]
Test
0.9220968879041193
[[18157    79]
 [ 1468   154]]
****************************************************************************************************
10
Train
0.9278720603152449
[[127297    751]
 [  9275   1680]]
Validation
0.9207604179780939
[[36221   333]
 [ 2814   347]]
Test
0.9202840165172727
[[18082   154]
 [ 1429   193]]
****************************************************************************************************
15
Train
0.9343467407178262
[[126798   1250]
 [  7876   3079]]
Validation
0.9132317764068991
[[35786   768]
 [ 2678   483]]
Test
0.9135864638936448
[[17882   354]
 [ 1362   260]]
****************************************************************************************************
20
Train
0.9387423293022453
[[126633   1415]
 [  7100   3855]

In [55]:
for i in range(5, 51, 5):
    clf= DecisionTreeClassifier(max_depth= i)
    clf.fit(X_train, y_train)
    print("*"*100)
    print(i)
    print("Train")
    print(accuracy_score(y_train, clf.predict(X_train)))
    print(confusion_matrix(y_train, clf.predict(X_train)))
    print("Validation")
    print(accuracy_score(y_valid, clf.predict(X_valid)))
    print(confusion_matrix(y_valid, clf.predict(X_valid)))
    print("Test")
    print(accuracy_score(y_test, clf.predict(X_test)))
    print(confusion_matrix(y_test, clf.predict(X_test)))

****************************************************************************************************
5
Train
0.9247498255433336
[[127537    511]
 [  9949   1006]]
Validation
0.922875487850938
[[36398   156]
 [ 2907   254]]
Test
0.9220968879041193
[[18157    79]
 [ 1468   154]]
****************************************************************************************************
10
Train
0.9305554556376481
[[127376    672]
 [  8981   1974]]
Validation
0.9207352385748457
[[36202   352]
 [ 2796   365]]
Test
0.9204854466713667
[[18069   167]
 [ 1412   210]]
****************************************************************************************************
15
Train
0.9480946454393071
[[127474    574]
 [  6641   4314]]
Validation
0.9096059423391666
[[35627   927]
 [ 2663   498]]
Test
0.9101621512740458
[[17805   431]
 [ 1353   269]]
****************************************************************************************************
20
Train
0.9691805212837133
[[127735    313]
 [  3971   6984]

In [61]:
for i in range(1, 15):
    clf= DecisionTreeClassifier(max_depth= i)
    clf.fit(X_train, y_train)
    print("*"*100)
    print(i)
    print("Train")
    print(accuracy_score(y_train, clf.predict(X_train)))
    print(confusion_matrix(y_train, clf.predict(X_train)))
    print("Validation")
    print(accuracy_score(y_valid, clf.predict(X_valid)))
    print(confusion_matrix(y_valid, clf.predict(X_valid)))
    print("Test")
    print(accuracy_score(y_test, clf.predict(X_test)))
    print(confusion_matrix(y_test, clf.predict(X_test)))

****************************************************************************************************
1
Train
0.9211887513219139
[[128048      0]
 [ 10955      0]]
Validation
0.9204079063326199
[[36554     0]
 [ 3161     0]]
Test
0.9183200725148555
[[18236     0]
 [ 1622     0]]
****************************************************************************************************
2
Train
0.9222103120076545
[[127038   1010]
 [  9803   1152]]
Validation
0.9206345209618532
[[36254   300]
 [ 2852   309]]
Test
0.9208379494410314
[[18104   132]
 [ 1440   182]]
****************************************************************************************************
3
Train
0.9238577584656447
[[127378    670]
 [  9914   1041]]
Validation
0.9220697469469974
[[36354   200]
 [ 2895   266]]
Test
0.9220968879041193
[[18148    88]
 [ 1459   163]]
****************************************************************************************************
4
Train
0.9245915555779372
[[127517    531]
 [  9951   1004]]


## Adaboost

In [11]:
from sklearn.ensemble import AdaBoostClassifier

In [76]:
for i in range(1, 5):
    decision_clf= DecisionTreeClassifier(max_depth= i)
    clf = AdaBoostClassifier(decision_clf, n_estimators=50, random_state=0)
    clf.fit(X_train, y_train)
    print("*"*100)
    print(i)
    print("Train")
    print(accuracy_score(y_train, clf.predict(X_train)))
    print(confusion_matrix(y_train, clf.predict(X_train)))
    print("Validation")
    print(accuracy_score(y_valid, clf.predict(X_valid)))
    print(confusion_matrix(y_valid, clf.predict(X_valid)))
    print("Test")
    print(accuracy_score(y_test, clf.predict(X_test)))
    print(confusion_matrix(y_test, clf.predict(X_test)))

****************************************************************************************************
1
Train
0.9170377617749257
[[126656   1392]
 [ 10140    815]]
Validation
0.9171849427168576
[[36184   370]
 [ 2919   242]]
Test
0.9157518380501561
[[18044   192]
 [ 1481   141]]
****************************************************************************************************
2
Train
0.9241383279497565
[[127178    870]
 [  9675   1280]]
Validation
0.9219942087372529
[[36266   288]
 [ 2810   351]]
Test
0.92139188236479
[[18101   135]
 [ 1426   196]]
****************************************************************************************************
3
Train
0.924800184168687
[[127080    968]
 [  9485   1470]]
Validation
0.9210373914138235
[[36225   329]
 [ 2807   354]]
Test
0.9217947426729781
[[18090   146]
 [ 1407   215]]
****************************************************************************************************
4
Train
0.9262461961252635
[[126733   1315]
 [  8937   2018]]
Val

In [12]:
for i in range(2, 6):
    decision_clf= DecisionTreeClassifier(max_depth= i)
    clf = AdaBoostClassifier(decision_clf, n_estimators=100, random_state=0, learning_rate= 0.5)
    clf.fit(X_train, y_train)
    print("*"*100)
    print(i)
    print("Train")
    print(accuracy_score(y_train, clf.predict(X_train)))
    print(confusion_matrix(y_train, clf.predict(X_train)))
    print("Validation")
    print(accuracy_score(y_valid, clf.predict(X_valid)))
    print(confusion_matrix(y_valid, clf.predict(X_valid)))
    print("Test")
    print(accuracy_score(y_test, clf.predict(X_test)))
    print(confusion_matrix(y_test, clf.predict(X_test)))

ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

In [27]:
for i in range(2, 6):
    decision_clf= DecisionTreeClassifier(max_depth= i)
    clf = AdaBoostClassifier(decision_clf, n_estimators= 154, num_leaves= 40, min_child_samples= 22, learning_rate= 0.04592957118721939)
    clf.fit(X_train, y_train)
    print("*"*100)
    print(i)
    print("Train")
    print(accuracy_score(y_train, clf.predict(X_train)))
    print(confusion_matrix(y_train, clf.predict(X_train)))
    print("Validation")
    print(accuracy_score(y_valid, clf.predict(X_valid)))
    print(confusion_matrix(y_valid, clf.predict(X_valid)))
    print("Test")
    print(accuracy_score(y_test, clf.predict(X_test)))
    print(confusion_matrix(y_test, clf.predict(X_test)))

TypeError: __init__() got an unexpected keyword argument 'num_leaves'

In [30]:
for i in range(2, 6):
    decision_clf= DecisionTreeClassifier(max_depth= i, min_samples_split= 22)
    clf = AdaBoostClassifier(decision_clf, n_estimators=100, random_state=0, learning_rate= 0.5)
    clf.fit(X_train, y_train)
    print("*"*100)
    print(i)
    print("Train")
    print(accuracy_score(y_train, clf.predict(X_train)))
    print(confusion_matrix(y_train, clf.predict(X_train)))
    print("Validation")
    print(accuracy_score(y_valid, clf.predict(X_valid)))
    print(confusion_matrix(y_valid, clf.predict(X_valid)))
    print("Test")
    print(accuracy_score(y_test, clf.predict(X_test)))
    print(confusion_matrix(y_test, clf.predict(X_test)))

****************************************************************************************************
2
Train
0.9525386560451118
[[41432   598]
 [ 1523  1136]]
Validation
0.9519110275689223
[[11858   166]
 [  448   296]]
Test
0.9454972592012529
[[5882  111]
 [ 237  155]]
****************************************************************************************************
3
Train
0.9598111392065162
[[41535   495]
 [ 1301  1358]]
Validation
0.949483082706767
[[11835   189]
 [  456   288]]
Test
0.9473766640563821
[[5886  107]
 [ 229  163]]
****************************************************************************************************
4
Train
0.9743113517867932
[[41701   329]
 [  819  1840]]
Validation
0.9458803258145363
[[11802   222]
 [  469   275]]
Test
0.9431480031323414
[[5873  120]
 [ 243  149]]
****************************************************************************************************
5
Train
0.9943162746984716
[[41940    90]
 [  164  2495]]
Validation
0.9429041353383458

In [83]:
for i in range(2, 6):
    decision_clf= DecisionTreeClassifier(max_depth= i, min_samples_split= 100)
    clf = AdaBoostClassifier(decision_clf, n_estimators=100, random_state=0, learning_rate= 0.5)
    clf.fit(X_train, y_train)
    print("*"*100)
    print(i)
    print("Train")
    print(accuracy_score(y_train, clf.predict(X_train)))
    print(confusion_matrix(y_train, clf.predict(X_train)))
    print("Validation")
    print(accuracy_score(y_valid, clf.predict(X_valid)))
    print(confusion_matrix(y_valid, clf.predict(X_valid)))
    print("Test")
    print(accuracy_score(y_test, clf.predict(X_test)))
    print(confusion_matrix(y_test, clf.predict(X_test)))

****************************************************************************************************
2
Train
0.9243253742724977
[[127440    608]
 [  9911   1044]]
Validation
0.9221452851567418
[[36353   201]
 [ 2891   270]]
Test
0.9222983180582133
[[18139    97]
 [ 1446   176]]
****************************************************************************************************
3
Train
0.9257138335143846
[[127305    743]
 [  9583   1372]]
Validation
0.9222460027697343
[[36291   263]
 [ 2825   336]]
Test
0.9226004632893544
[[18122   114]
 [ 1423   199]]
****************************************************************************************************
4
Train
0.927944001208607
[[127178    870]
 [  9146   1809]]
Validation
0.9223215409794788
[[36262   292]
 [ 2793   368]]
Test
0.9222479605196898
[[18086   150]
 [ 1394   228]]
****************************************************************************************************
5
Train
0.9315914045020611
[[127141    907]
 [  8602   2353]]
V

In [84]:
for i in range(2, 6):
    decision_clf= DecisionTreeClassifier(max_depth= i, min_samples_split= 100, splitter= 'random')
    clf = AdaBoostClassifier(decision_clf, n_estimators=100, random_state=0, learning_rate= 0.5)
    clf.fit(X_train, y_train)
    print("*"*100)
    print(i)
    print("Train")
    print(accuracy_score(y_train, clf.predict(X_train)))
    print(confusion_matrix(y_train, clf.predict(X_train)))
    print("Validation")
    print(accuracy_score(y_valid, clf.predict(X_valid)))
    print(confusion_matrix(y_valid, clf.predict(X_valid)))
    print("Test")
    print(accuracy_score(y_test, clf.predict(X_test)))
    print(confusion_matrix(y_test, clf.predict(X_test)))

****************************************************************************************************
2
Train
0.9219297425235427
[[127782    266]
 [ 10586    369]]
Validation
0.9208611355910865
[[36474    80]
 [ 3063    98]]
Test
0.9188236479000906
[[18193    43]
 [ 1569    53]]
****************************************************************************************************
3
Train
0.9240591929670583
[[127405    643]
 [  9913   1042]]
Validation
0.921843132317764
[[36343   211]
 [ 2893   268]]
Test
0.921291167287743
[[18139    97]
 [ 1466   156]]
****************************************************************************************************
4
Train
0.9250232009381093
[[127254    794]
 [  9628   1327]]
Validation
0.9222963615762306
[[36304   250]
 [ 2836   325]]
Test
0.9218451002115017
[[18110   126]
 [ 1426   196]]
****************************************************************************************************
5
Train
0.9262965547506169
[[127318    730]
 [  9515   1440]]
Va

In [87]:
for i in range(2, 6):
    decision_clf= DecisionTreeClassifier(max_depth= i, splitter= 'random')
    clf = AdaBoostClassifier(decision_clf, n_estimators=200, random_state=0, learning_rate= 0.5)
    clf.fit(X_train, y_train)
    print("*"*100)
    print(i)
    print("Train")
    print(accuracy_score(y_train, clf.predict(X_train)))
    print(confusion_matrix(y_train, clf.predict(X_train)))
    print("Validation")
    print(accuracy_score(y_valid, clf.predict(X_valid)))
    print(confusion_matrix(y_valid, clf.predict(X_valid)))
    print("Test")
    print(accuracy_score(y_test, clf.predict(X_test)))
    print(confusion_matrix(y_test, clf.predict(X_test)))

****************************************************************************************************
2
Train
0.9233182017654296
[[127498    550]
 [ 10109    846]]
Validation
0.921465441269042
[[36372   182]
 [ 2937   224]]
Test
0.9208883069795548
[[18164    72]
 [ 1499   123]]
****************************************************************************************************
3
Train
0.9251670827248333
[[127360    688]
 [  9714   1241]]
Validation
0.9213395442528012
[[36310   244]
 [ 2880   281]]
Test
0.921089737133649
[[18121   115]
 [ 1452   170]]
****************************************************************************************************
4
Train
0.9272389804536593
[[127269    779]
 [  9335   1620]]
Validation
0.9203827269293717
[[36231   323]
 [ 2839   322]]
Test
0.9211400946721724
[[18091   145]
 [ 1421   201]]
****************************************************************************************************
5
Train
0.9311022064271994
[[127225    823]
 [  8754   2201]]
Va

## Load imbalance

In [19]:
from collections import Counter

counter = Counter(y_train)
counter
smote_oversample = SMOTE(sampling_strategy=0.5)
#random_undersample = RandomUnderSampler(sampling_strategy=0.9)
#steps = [('o', smote_oversample), ('u', random_undersample)]
#pipeline_sample = Pipeline(steps=steps)
#X3, y3 = pipeline_sample.fit_resample(X_train2,y_train2)
X3, y3 = smote_oversample.fit_resample(X_train,y_train)
counter = Counter(y3)
counter
X_train5, X_test5, y_train5, y_test5 = train_test_split(X3,y3, test_size=0.2, train_size=0.8, random_state=7)

In [13]:
for i in range(2, 6):
    decision_clf= DecisionTreeClassifier(max_depth= i)
    clf = AdaBoostClassifier(decision_clf, n_estimators=100, random_state=0, learning_rate= 0.5)
    clf.fit(X_train5, y_train5)
    print("*"*100)
    print(i)
    print("Train")
    print(accuracy_score(y_train5, clf.predict(X_train5)))
    print(confusion_matrix(y_train5, clf.predict(X_train5)))
#     print("Validation")
#     print(accuracy_score(y_valid5, clf.predict(X_valid5)))
#     print(confusion_matrix(y_valid5, clf.predict(X_valid)))
    print("Test")
    print(accuracy_score(y_test5, clf.predict(X_test5)))
    print(confusion_matrix(y_test5, clf.predict(X_test5)))
    print("-"*100)
    print(i)
    print("True Train")
    print(accuracy_score(y_train, clf.predict(X_train)))
    print(confusion_matrix(y_train, clf.predict(X_train)))
    print("True Validation")
    print(accuracy_score(y_valid, clf.predict(X_valid)))
    print(confusion_matrix(y_valid, clf.predict(X_valid)))
    print("True Test")
    print(accuracy_score(y_test, clf.predict(X_test)))
    print(confusion_matrix(y_test, clf.predict(X_test)))

****************************************************************************************************
2
Train
0.8811248429944617
[[95103  7402]
 [10864 40288]]
Test
0.8771833919042041
[[23658  1885]
 [ 2833 10039]]
----------------------------------------------------------------------------------------------------
2
True Train
0.8819090235462544
[[118761   9287]
 [  7128   3827]]
True Validation
0.8817323429434722
[[33907  2647]
 [ 2050  1111]]
True Test
0.8791922650820828
[[16889  1347]
 [ 1052   570]]
****************************************************************************************************
3
Train
0.8968481748309547
[[96235  6270]
 [ 9580 41572]]
Test
0.8913965898737473
[[23882  1661]
 [ 2511 10361]]
----------------------------------------------------------------------------------------------------
3
True Train
0.8911030697179197
[[120117   7931]
 [  7206   3749]]
True Validation
0.888203449578245
[[34230  2324]
 [ 2116  1045]]
True Test
0.8875012589384631
[[17080  1156]
 

In [17]:
for i in range(2, 5):
    decision_clf= DecisionTreeClassifier(max_depth= i)
    clf = AdaBoostClassifier(decision_clf, n_estimators=50, random_state=0, learning_rate= 1)
    clf.fit(X_train5, y_train5)
    print("*"*100)
    print(i)
    print("Train")
    print(accuracy_score(y_train5, clf.predict(X_train5)))
    print(confusion_matrix(y_train5, clf.predict(X_train5)))
#     print("Validation")
#     print(accuracy_score(y_valid5, clf.predict(X_valid5)))
#     print(confusion_matrix(y_valid5, clf.predict(X_valid)))
    print("Test")
    print(accuracy_score(y_test5, clf.predict(X_test5)))
    print(confusion_matrix(y_test5, clf.predict(X_test5)))
    print("-"*100)
    print(i)
    print("True Train")
    print(accuracy_score(y_train, clf.predict(X_train)))
    print(confusion_matrix(y_train, clf.predict(X_train)))
    print("True Validation")
    print(accuracy_score(y_valid, clf.predict(X_valid)))
    print(confusion_matrix(y_valid, clf.predict(X_valid)))
    print("True Test")
    print(accuracy_score(y_test, clf.predict(X_test)))
    print(confusion_matrix(y_test, clf.predict(X_test)))

****************************************************************************************************
2
Train
0.8713368086061813
[[94006  8499]
 [11271 39881]]
Test
0.8671612651308083
[[23384  2159]
 [ 2944  9928]]
----------------------------------------------------------------------------------------------------
2
True Train
0.8723049142824255
[[117390  10658]
 [  7092   3863]]
True Validation
0.8718620168702002
[[33522  3032]
 [ 2057  1104]]
True Test
0.8708832712257025
[[16710  1526]
 [ 1038   584]]
****************************************************************************************************
3
Train
0.8864679122981706
[[94985  7520]
 [ 9925 41227]]
Test
0.8799166992060393
[[23572  1971]
 [ 2642 10230]]
----------------------------------------------------------------------------------------------------
3
True Train
0.8805493406617123
[[118557   9491]
 [  7113   3842]]
True Validation
0.8799949641193504
[[33891  2663]
 [ 2103  1058]]
True Test
0.8770268909255715
[[16858  1378]


In [21]:
for i in range(1, 5):
    decision_clf= DecisionTreeClassifier(max_depth= i)
    clf = AdaBoostClassifier(decision_clf, n_estimators=100, random_state=0, learning_rate= 1)
    clf.fit(X_train5, y_train5)
    print("*"*100)
    print(i)
    print("Train")
    print(accuracy_score(y_train5, clf.predict(X_train5)))
    print(confusion_matrix(y_train5, clf.predict(X_train5)))
#     print("Validation")
#     print(accuracy_score(y_valid5, clf.predict(X_valid5)))
#     print(confusion_matrix(y_valid5, clf.predict(X_valid)))
    print("Test")
    print(accuracy_score(y_test5, clf.predict(X_test5)))
    print(confusion_matrix(y_test5, clf.predict(X_test5)))
    print("-"*100)
    print(i)
    print("True Train")
    print(accuracy_score(y_train, clf.predict(X_train)))
    print(confusion_matrix(y_train, clf.predict(X_train)))
    print("True Validation")
    print(accuracy_score(y_valid, clf.predict(X_valid)))
    print(confusion_matrix(y_valid, clf.predict(X_valid)))
    print("True Test")
    print(accuracy_score(y_test, clf.predict(X_test)))
    print(confusion_matrix(y_test, clf.predict(X_test)))

****************************************************************************************************
1
Train
0.8663982102908278
[[98461  4023]
 [12400  8041]]
Test
0.86300924118183
[[24549  1015]
 [ 3195  1973]]
----------------------------------------------------------------------------------------------------
1
True Train
0.9009949425551966
[[123010   5038]
 [  8724   2231]]
True Validation
0.9006672541860757
[[35109  1445]
 [ 2500   661]]
True Test
0.9003424312619599
[[17521   715]
 [ 1264   358]]
****************************************************************************************************
2
Train
0.8936424649176327
[[98941  3543]
 [ 9531 10910]]
Test
0.8895939086294417
[[24624   940]
 [ 2453  2715]]
----------------------------------------------------------------------------------------------------
2
True Train
0.9083185254994497
[[123565   4483]
 [  8261   2694]]
True Validation
0.9059801082714339
[[35251  1303]
 [ 2431   730]]
True Test
0.9038674589586061
[[17554   682]
 [

KeyboardInterrupt: 

In [26]:
for i in range(2, 3):
    decision_clf= DecisionTreeClassifier(max_depth= i, splitter="random")
    clf = AdaBoostClassifier(decision_clf, n_estimators=200, random_state=0, learning_rate= 0.5)
    clf.fit(X_train5, y_train5)
    print("*"*100)
    print(i)
    print("Train")
    print(accuracy_score(y_train5, clf.predict(X_train5)))
    print(confusion_matrix(y_train5, clf.predict(X_train5)))
#     print("Validation")
#     print(accuracy_score(y_valid5, clf.predict(X_valid5)))
#     print(confusion_matrix(y_valid5, clf.predict(X_valid)))
    print("Test")
    print(accuracy_score(y_test5, clf.predict(X_test5)))
    print(confusion_matrix(y_test5, clf.predict(X_test5)))
    print("-"*100)
    print(i)
    print("True Train")
    print(accuracy_score(y_train, clf.predict(X_train)))
    print(confusion_matrix(y_train, clf.predict(X_train)))
    print("True Validation")
    print(accuracy_score(y_valid, clf.predict(X_valid)))
    print(confusion_matrix(y_valid, clf.predict(X_valid)))
    print("True Test")
    print(accuracy_score(y_test, clf.predict(X_test)))
    print(confusion_matrix(y_test, clf.predict(X_test)))

****************************************************************************************************
2
Train
0.8226131852398204
[[94339  8075]
 [16456 19421]]
Test
0.8202354438434617
[[23589  2045]
 [ 4170  4769]]
----------------------------------------------------------------------------------------------------
2
True Train
0.8783695315928434
[[117928  10120]
 [  6787   4168]]
True Validation
0.8764446682613622
[[33610  2944]
 [ 1963  1198]]
True Test
0.8750125893846309
[[16768  1468]
 [ 1014   608]]


In [7]:
import lightgbm as lgb

clf= lgb.LGBMClassifier(n_estimators= 154, num_leaves= 40, min_child_samples= 22, learning_rate= 0.04592957118721939, colsample_bytree= 0.6733735675646831, reg_alpha= 0.0009765625, reg_lambda= 18.492718255154934)

In [8]:
clf.fit(X_train, y_train)

LGBMClassifier(colsample_bytree=0.6733735675646831,
               learning_rate=0.04592957118721939, min_child_samples=22,
               n_estimators=154, num_leaves=40, reg_alpha=0.0009765625,
               reg_lambda=18.492718255154934)

In [9]:

print("-"*100)
print()
print("True Train")
print(accuracy_score(y_train, clf.predict(X_train)))
print(confusion_matrix(y_train, clf.predict(X_train)))
print("True Validation")
print(accuracy_score(y_valid, clf.predict(X_valid)))
print(confusion_matrix(y_valid, clf.predict(X_valid)))
print("True Test")
print(accuracy_score(y_test, clf.predict(X_test)))
print(confusion_matrix(y_test, clf.predict(X_test)))

----------------------------------------------------------------------------------------------------

True Train
0.9513255372558623
[[43152   817]
 [ 1568  3462]]
True Validation
0.9458571428571428
[[12305   261]
 [  497   937]]
True Test
0.9467142857142857
[[6187  145]
 [ 228  440]]


In [33]:
from sklearn.neighbors import KNeighborsClassifier

In [37]:
neigh = KNeighborsClassifier(n_neighbors=1)
neigh.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=1)

In [39]:
print("-"*100)
print()
print("True Train")
#y_pred= neigh.predict(X_train)
#print(accuracy_score(y_train, y_pred))
#print(confusion_matrix(y_train, y_pred))
print("True Validation")
y_pred= neigh.predict(X_valid)
print(accuracy_score(y_valid, y_pred))
print(confusion_matrix(y_valid, y_pred))
print("True Test")
print(accuracy_score(y_test, neigh.predict(X_test)))
print(confusion_matrix(y_test, neigh.predict(X_test)))

----------------------------------------------------------------------------------------------------

True Train
True Validation
0.8758403625834068
[[34128  2426]
 [ 2505   656]]
True Test
0.8760197401551012
[[17049  1187]
 [ 1275   347]]


In [6]:
X_train

arpu_6   arpu_7   arpu_8  onnet_mou_6  onnet_mou_7  onnet_mou_8  \
50431  152.248   44.160  164.759       128.98         4.55       236.63   
21088   81.105   57.893   66.787        58.04        22.71        31.76   
29540   33.728  512.489  141.696         0.75       304.76       231.54   
39514  272.667  339.824  370.292        43.01        64.26        22.89   
63608  260.107  512.826  407.659       379.59        98.81       229.96   
...        ...      ...      ...          ...          ...          ...   
59465  272.144  388.837  310.270       148.51       121.86       119.01   
5520   313.370  256.778  279.315        76.86        43.94        25.01   
20463  300.984  185.459  188.832        22.78        14.24        27.93   
18638  282.335  207.521  272.111         9.99         2.38        12.94   
35683  657.940  660.067  681.706       105.09        78.68        83.51   

       offnet_mou_6  offnet_mou_7  offnet_mou_8  roam_ic_mou_6  ...  \
50431         64.54         44.81         71.49           0.30  ...   
21088         15.83         32.06         34.46           0.00  ...   
29540          3.83        316.56        319.89           0.00  ...   
39514        161.59        210.89        199.81          18.44  ...   
63608         77.84        181.46        158.83           0.00  ...   
...             ...           ...           ...            ...  ...   
59465        477.08        425.94        501.86           0.00  ...   
5520         325.34        225.84        143.46          19.28  ...   
20463        337.13        206.94        195.29           0.00  ...   
18638        121.64        105.64        100.33           0.00  ...   
35683        745.08        684.31        891.11           0.00  ...   

       monthly_3g_6  monthly_3g_7  monthly_3g_8  sachet_3g_6  sachet_3g_7  \
50431             0             0             0            0            0   
21088             0             0             0            0            0   
29540             0             0             0            0            0   
39514             0             0             0            0            0   
63608             0             0             0            0            0   
...             ...           ...           ...          ...          ...   
59465             0             0             0            0            0   
5520              0             0             0            0            0   
20463             0             0             0            0            0   
18638             0             0             0            0            0   
35683             0             0             0            0            0   

       sachet_3g_8   aon  aug_vbc_3g  jul_vbc_3g  jun_vbc_3g  
50431            0  1076         0.0        0.00         0.0  
21088            0   514         0.0        0.00         0.0  
29540            0   244         0.0        0.00         0.0  
39514            0   759         0.0       20.16         0.0  
63608            0   356         0.0        0.00         0.0  
...            ...   ...         ...         ...         ...  
59465            0  1188         0.0        0.00         0.0  
5520             0  3034         0.0        0.00         0.0  
20463            0  2226         0.0        0.00         0.0  
18638            0  3112         0.0        0.00         0.0  
35683            0   686         0.0        0.00         0.0  

[48999 rows x 124 columns]