In [1]:
# Importing the necessary packages
import pandas as pd
import numpy as np
from imblearn.over_sampling import SMOTE

# To ensure all outputs from a cell are shown
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

# To ensure all columns of a dataframe are shown
pd.set_option("display.max_columns", None)

In [2]:
df = pd.read_csv("tidy_data.csv")
df

id  month  jun_vbc_3g  jul_vbc_3g  aug_vbc_3g  churn_probability  \
0            0      6        0.00        0.00        0.00                  0   
1            1      6        0.00        0.00        0.00                  0   
2            2      6        0.00        0.00        0.00                  0   
3            3      6        0.00        0.00        0.00                  0   
4            4      6        0.00        0.00        0.00                  0   
...        ...    ...         ...         ...         ...                ...   
209992  209992      8        0.00        0.00        0.00                  0   
209993  209993      8        0.00        0.00        0.00                  0   
209994  209994      8        0.00        0.00        0.00                  0   
209995  209995      8      990.97     1402.96      664.25                  0   
209996  209996      8        0.00        0.00        0.00                  0   

         aon     arpu  onnet_mou  offnet_mou  roam_ic_mou  roam_og_mou  \
0       1958   31.277      48.58       32.24         0.00         0.00   
1        710    0.000       0.00        0.00         0.00         0.00   
2        882   60.806       0.53       53.99         0.00         0.00   
3        982  156.362       7.26       68.76         0.00         0.00   
4        647  240.708      21.28       56.99        53.64        15.73   
...      ...      ...        ...         ...          ...          ...   
209992   221  329.136      10.93      381.64         0.00         0.00   
209993   712  265.772     232.63       48.06         0.00         0.00   
209994   879  279.782      78.44      263.84         0.00         0.00   
209995   277  145.062       6.71       12.56         0.00         0.00   
209996  1876  167.961       0.00        0.00         0.00         0.00   

        loc_og_t2t_mou  loc_og_t2m_mou  loc_og_t2f_mou  loc_og_t2c_mou  \
0                 2.23            5.29            0.00            0.00   
1                 0.00            0.00            0.00            0.00   
2                 0.53           24.11            0.00            2.14   
3                 6.99           37.91            0.00            0.00   
4                10.16           36.74           11.99            0.00   
...                ...             ...             ...             ...   
209992            7.19           89.66            0.00            0.86   
209993            9.06           47.34            0.00            0.00   
209994           78.44          138.26          125.58            0.00   
209995            6.71            8.84            2.86            0.00   
209996            0.00            0.00            0.00            0.00   

        loc_og_mou  std_og_t2t_mou  std_og_t2m_mou  std_og_t2f_mou  \
0             7.53           46.34           18.75            0.00   
1             0.00            0.00            0.00            0.00   
2            24.64            0.00           28.94            0.00   
3            44.91            0.26           15.33            0.56   
4            58.91            0.00            4.35            0.00   
...            ...             ...             ...             ...   
209992       96.86            3.73          290.14            0.00   
209993       56.41          223.56            0.53            0.00   
209994      342.29            0.00            0.00            0.00   
209995       18.43            0.00            0.85            0.00   
209996        0.00            0.00            0.00            0.00   

        std_og_mou  isd_og_mou  spl_og_mou  og_others  total_og_mou  \
0            65.09         0.0        8.20       0.38         81.21   
1             0.00         0.0        0.00       0.00          0.00   
2            28.94         0.0        2.89       0.00         56.49   
3            16.16         0.0       14.95       0.00         76.03   
4             4.35         0.0        0.00       0.00         63.26   
...   

In [3]:
df=df.dropna()

In [4]:
df=df.drop(["id","date_of_last_rech"],axis=1)

In [5]:
df

month  jun_vbc_3g  jul_vbc_3g  aug_vbc_3g  churn_probability   aon  \
0           6        0.00        0.00        0.00                  0  1958   
1           6        0.00        0.00        0.00                  0   710   
2           6        0.00        0.00        0.00                  0   882   
3           6        0.00        0.00        0.00                  0   982   
4           6        0.00        0.00        0.00                  0   647   
...       ...         ...         ...         ...                ...   ...   
209992      8        0.00        0.00        0.00                  0   221   
209993      8        0.00        0.00        0.00                  0   712   
209994      8        0.00        0.00        0.00                  0   879   
209995      8      990.97     1402.96      664.25                  0   277   
209996      8        0.00        0.00        0.00                  0  1876   

           arpu  onnet_mou  offnet_mou  roam_ic_mou  roam_og_mou  \
0        31.277      48.58       32.24         0.00         0.00   
1         0.000       0.00        0.00         0.00         0.00   
2        60.806       0.53       53.99         0.00         0.00   
3       156.362       7.26       68.76         0.00         0.00   
4       240.708      21.28       56.99        53.64        15.73   
...         ...        ...         ...          ...          ...   
209992  329.136      10.93      381.64         0.00         0.00   
209993  265.772     232.63       48.06         0.00         0.00   
209994  279.782      78.44      263.84         0.00         0.00   
209995  145.062       6.71       12.56         0.00         0.00   
209996  167.961       0.00        0.00         0.00         0.00   

        loc_og_t2t_mou  loc_og_t2m_mou  loc_og_t2f_mou  loc_og_t2c_mou  \
0                 2.23            5.29            0.00            0.00   
1                 0.00            0.00            0.00            0.00   
2                 0.53           24.11            0.00            2.14   
3                 6.99           37.91            0.00            0.00   
4                10.16           36.74           11.99            0.00   
...                ...             ...             ...             ...   
209992            7.19           89.66            0.00            0.86   
209993            9.06           47.34            0.00            0.00   
209994           78.44          138.26          125.58            0.00   
209995            6.71            8.84            2.86            0.00   
209996            0.00            0.00            0.00            0.00   

        loc_og_mou  std_og_t2t_mou  std_og_t2m_mou  std_og_t2f_mou  \
0             7.53           46.34           18.75            0.00   
1             0.00            0.00            0.00            0.00   
2            24.64            0.00           28.94            0.00   
3            44.91            0.26           15.33            0.56   
4            58.91            0.00            4.35            0.00   
...            ...             ...             ...             ...   
209992       96.86            3.73          290.14            0.00   
209993       56.41          223.56            0.53            0.00   
209994      342.29            0.00            0.00            0.00   
209995       18.43            0.00            0.85            0.00   
209996        0.00            0.00            0.00            0.00   

        std_og_mou  isd_og_mou  spl_og_mou  og_others  total_og_mou  \
0            65.09         0.0        8.20       0.38         81.21   
1             0.00         0.0        0.00       0.00          0.00   
2            28.94         0.0        2.89       0.00         56.49   
3            16.16         0.0       14.95       0.00         76.03   
4             4.35         0.0        0.00       0.00         63.26   
...            ...         ...         ...        ...           ...   
209992      293.88         

In [23]:
# Install the fast_ml package for splitting the dataset
#!pip install fast_ml

In [22]:
from fast_ml.model_development import train_valid_test_split

# Splitting the data into Training, validation and test sets
X_train, y_train, X_valid, y_valid, X_test, y_test = train_valid_test_split(df, target = "churn_probability", 
                                                                            train_size=0.7, valid_size=0.2, test_size=0.1, random_state=5)

# Display a few of the data sets
X_train
X_test
y_test

month  jun_vbc_3g  jul_vbc_3g  aug_vbc_3g   aon     arpu  onnet_mou  \
63326       6        0.00        0.00        0.00   291  797.579     232.23   
90060       7        0.00        0.00        0.00  2942  572.551     156.34   
197881      8        0.00        0.00        0.00   856  109.006      44.48   
58680       6      105.23      215.33       38.81   495  247.896     112.28   
30666       6        0.00        0.00        0.00   215  408.460      40.44   
...       ...         ...         ...         ...   ...      ...        ...   
128030      7        0.00        0.00        0.00   838   74.203      24.78   
130790      7       61.11       56.79       51.07   390   82.781       0.00   
21484       6        0.00        0.00        0.00   786  148.781      22.69   
19552       6        0.00        0.00        0.00   894  444.203     212.64   
37468       6        0.00        0.00        0.00   439  130.926      56.21   

        offnet_mou  roam_ic_mou  roam_og_mou  loc_og_t2t_mou  loc_og_t2m_mou  \
63326      1367.91          0.0         0.00           49.59           77.04   
90060       158.84          0.0         0.00          149.84           84.14   
197881       26.41          0.0         0.00           42.18           21.58   
58680        17.28          0.0         0.00          112.28           10.76   
30666       465.58          0.3         3.16           29.63          193.74   
...            ...          ...          ...             ...             ...   
128030       78.43          0.0         0.00           24.78           77.98   
130790        0.15          0.0         0.00            0.00            0.00   
21484        96.04          0.0         0.00           22.69           96.04   
19552       359.24          0.0         0.00           91.21           38.78   
37468        61.44          0.0         0.00           56.21           34.84   

        loc_og_t2f_mou  loc_og_t2c_mou  loc_og_mou  std_og_t2t_mou  \
63326             0.00            6.33      126.64          182.63   
90060             2.53            4.15      236.53            6.49   
197881            0.90            0.00       64.66            2.30   
58680             0.00            0.00      123.04            0.00   
30666             4.26            0.00      227.64           10.81   
...                ...             ...         ...             ...   
128030            0.45            0.00      103.21            0.00   
130790            0.00            0.00        0.00            0.00   
21484             0.00            0.00      118.74            0.00   
19552             0.00            0.00      129.99          121.43   
37468            26.51            0.00      117.58            0.00   

        std_og_t2m_mou  std_og_t2f_mou  std_og_mou  isd_og_mou  spl_og_mou  \
63326          1260.73            0.88     1444.24        0.00       30.83   
90060            52.03            0.00       58.53        0.00       24.89   
197881            3.93            0.00        6.23        0.00        0.55   
58680             6.51            0.00        6.51        0.00        0.00   
30666           266.24            0.00      277.06        0.28        5.99   
...                ...             ...         ...         ...         ...   
128030            0.00            0.00        0.00        0.00        0.00   
130790            0.00            0.00        0.00        0.00        0.15   
21484             0.00            0.00        0.00        0.00        0.53   
19552           320.46            0.00      441.89        0.00        0.00   
37468             0.00            0.00        0.00        0.00        0.19   

        og_others  total_og_mou  loc_ic_t2t_mou  loc_ic_t2m_mou  \
63326        0.00       1601.73          133.13          196.64   
90060        0.00        319.96           86.08          113.58   
197881       0.00         71.44          128.68           20.28   
58680        0.00        129.56           63.31     

month  jun_vbc_3g  jul_vbc_3g  aug_vbc_3g   aon      arpu  onnet_mou  \
179035      8        0.00        0.00        0.00   248    36.456       3.93   
75904       7        0.00        0.00        0.00   747   365.417     212.14   
167460      8        0.00        0.00        0.00   600   343.672      50.81   
13741       6     1026.99      408.33      162.71   958   537.299      25.71   
123691      7        0.00        0.00        0.00   944    62.808      51.33   
...       ...         ...         ...         ...   ...       ...        ...   
83843       7        0.00        0.00        0.00  2372   209.745      65.93   
27774       6        0.00       48.08      107.91  2263   256.323      18.73   
114607      7        0.00        0.00      345.78   401  1299.471    1040.63   
141081      8        0.00        0.38        0.32  1284   136.370       0.00   
200351      8      104.55       96.60      358.66   192    85.772       0.00   

        offnet_mou  roam_ic_mou  roam_og_mou  loc_og_t2t_mou  loc_og_t2m_mou  \
179035       31.98         0.00         0.00            3.93           16.64   
75904       175.11       142.44       387.26            0.00            0.00   
167460      338.28         0.00         0.00           50.81          133.73   
13741       181.06         0.00         0.00            9.41          102.04   
123691        7.90         0.00         0.00            2.54            7.06   
...            ...          ...          ...             ...             ...   
83843       119.41        18.73         6.94           40.96           76.29   
27774       124.68         0.00         0.00           18.73          109.64   
114607      593.39         2.23        29.64           95.13          199.43   
141081       97.26        31.26        33.71            0.00            2.35   
200351        0.00         0.00         0.00            0.00            0.00   

        loc_og_t2f_mou  loc_og_t2c_mou  loc_og_mou  std_og_t2t_mou  \
179035            0.00            0.00       20.58            0.00   
75904             0.00            0.00        0.00            0.00   
167460            0.00            0.00      184.54            0.00   
13741             0.00            0.00      111.46           16.29   
123691            0.00            0.00        9.61           48.78   
...                ...             ...         ...             ...   
83843             0.00            0.00      117.26           21.98   
27774             0.00           11.83      128.38            0.00   
114607            0.00            0.00      294.56          924.54   
141081            1.45            0.00        3.80            0.00   
200351            0.00            0.00        0.00            0.00   

        std_og_t2m_mou  std_og_t2f_mou  std_og_mou  isd_og_mou  spl_og_mou  \
179035           15.33            0.00       15.33         0.0        0.00   
75904             0.00            0.00        0.00         0.0        0.00   
167460          201.83            0.00      201.83         0.0        3.46   
13741            66.73            0.00       83.03         0.0       12.96   
123691            0.83            0.00       49.61         0.0        0.45   
...                ...             ...         ...         ...         ...   
83843            39.14            0.00       61.13         0.0        0.00   
27774             0.00            0.00        0.00         0.0       15.03   
114607          376.81            0.00     1301.36         0.0       13.19   
141081           47.58           12.16       59.74         0.0        0.00   
200351            0.00            0.00        0.00         0.0        0.00   

        og_others  total_og_mou  loc_ic_t2t_mou  loc_ic_t2m_mou  \
179035       0.00         35.91            2.28            1.59   
75904        0.00          0.00            0.00            0.00   
167460       0.00        389.84           33.31           54.09   
13741        0.83        208.29         

179035    0
75904     0
167460    0
13741     0
123691    0
         ..
83843     1
27774     0
114607    0
141081    0
200351    0
Name: churn_probability, Length: 19858, dtype: int64

In [7]:
# Training using the Random Forest Regressor

# Importing the model
from sklearn.ensemble import RandomForestClassifier

# Creating the model
modelRF = RandomForestClassifier(n_estimators=100, random_state=7)


# Fitting the model
modelRF.fit(X_train,y_train)

RandomForestClassifier(random_state=7)

In [12]:
from sklearn.metrics import accuracy_score

# Predicting Values for the training set
predsRFTrain = modelRF.predict(X_train)
print("Training Accuracy:")
accuracy_score(y_train, predsRFTrain)


# Predicting the values for validation set
predsRF = modelRF.predict(X_valid)

# Validation error
print("\nValidation Accuracy:")
accuracy_score(y_valid, predsRF)


# Predicting the values for the test set
predsRF2 = modelRF.predict(X_test)

print("\nTest Accuracy:")
accuracy_score(y_test, predsRF2)


Training Accuracy:


0.9999784177319914


Validation Accuracy:


0.9229258466574343


Test Accuracy:


0.9220968879041193

In [13]:
from sklearn.metrics import confusion_matrix

# Predicting Values for the training set
predsRFTrain = modelRF.predict(X_train)
print("Training Confusion Matrix:")
confusion_matrix(y_train, predsRFTrain)


# Predicting the values for validation set
predsRF = modelRF.predict(X_valid)

# Validation error
print("\nValidation Confusion Matrix:")
confusion_matrix(y_valid, predsRF)


# Predicting the values for the test set
predsRF2 = modelRF.predict(X_test)

print("\nTest Confusion Matrix:")
confusion_matrix(y_test, predsRF2)

Training Confusion Matrix:


array([[128048,      0],
       [     3,  10952]])


Validation Confusion Matrix:


array([[36352,   202],
       [ 2859,   302]])


Test Confusion Matrix:


array([[18133,   103],
       [ 1444,   178]])

In [66]:
# Hyperparameter Tuning for Random Forest Regressor
from sklearn.model_selection import RandomizedSearchCV

# Hyperparameters:
n_estimators = [int(i) for i in np.linspace(start = 100, stop = 200, num = 5)]

max_features =['auto','sqrt']

max_depth = [int(i) for i in np.linspace(10,50, num = 5)]
max_depth.append(None)

min_samples_split = [2,5,10]

#min_samples_leaf = [1,2,5]

#bootstrap = [True,False]

param_grid = {"n_estimators": n_estimators, "max_features": max_features, "max_depth": max_depth, 
              "min_samples_split": min_samples_split}

In [23]:
from sklearn.model_selection import train_test_split

X=df.drop(["churn_probability"],axis=1)
y=df["churn_probability"]
X_train2, X_test2, y_train2, y_test2 = train_test_split(X,y, test_size=0.2, train_size=0.8, random_state=5)


In [68]:
# Defining the model
RF2 = RandomForestClassifier()

# Hyperparameter tuning using randomizedsearch
modelRF2 = RandomizedSearchCV(estimator=RF2, param_distributions=param_grid, n_iter=10, cv=3, verbose=100, random_state=7, n_jobs=-1)

# Fitting the model
modelRF2.fit(X_train2, y_train2)

# Getting the best parameters
modelRF2.best_params_

Fitting 3 folds for each of 10 candidates, totalling 30 fits


RandomizedSearchCV(cv=3, estimator=RandomForestClassifier(), n_jobs=-1,
                   param_distributions={'max_depth': [10, 20, 30, 40, 50, None],
                                        'max_features': ['auto', 'sqrt'],
                                        'min_samples_split': [2, 5, 10],
                                        'n_estimators': [100, 125, 150, 175,
                                                         200]},
                   random_state=7, verbose=100)

{'n_estimators': 150,
 'min_samples_split': 2,
 'max_features': 'auto',
 'max_depth': 20}

In [72]:
best_RFmodel = modelRF2.best_estimator_

RFpredstrain = best_RFmodel.predict(X_train2)

print("\nTraining Confusion Matrix:")
confusion_matrix(y_train2,RFpredstrain)
print("\nTest Accuracy:")
accuracy_score(y_train2, RFpredstrain)

RFpreds = best_RFmodel.predict(X_test2)

print("\nTest Confusion Matrix:")
confusion_matrix(y_test2,RFpreds)

print("\nTest Accuracy:")
accuracy_score(y_test2, RFpreds)


Training Confusion Matrix:


array([[146043,    247],
       [  6476,   6094]])


Test Accuracy:


0.9576797179906836


Test Confusion Matrix:


array([[36351,   197],
       [ 2854,   314]])


Test Accuracy:


0.9231795749823749

In [10]:
# SVM with class weights

from sklearn.svm import SVC

# define model
modelSVC = SVC(gamma='scale', class_weight='balanced')
modelSVC.fit(X_train2,y_train2)


SVC(class_weight='balanced')

In [15]:
RFpredstrain = modelSVC.predict(X_train2)

print("\nTraining Confusion Matrix:")
confusion_matrix(y_train2,RFpredstrain)
print("\nTest Accuracy:")
accuracy_score(y_train2, RFpredstrain)

RFpreds = modelSVC.predict(X_test2)

print("\nTest Confusion Matrix:")
confusion_matrix(y_test2,RFpreds)

print("\nTest Accuracy:")
accuracy_score(y_test2, RFpreds)


Training Confusion Matrix:


array([[93359, 52931],
       [ 2668,  9902]])


Test Accuracy:


0.6500125897016241


Test Confusion Matrix:


array([[23120, 13428],
       [  767,  2401]])


Test Accuracy:


0.6425873703293383

In [8]:
from collections import Counter
counter = Counter(y)
counter

Counter({0: 182838, 1: 15738})

In [19]:
#!pip install imbalanced-learn

     |████████████████████████████████| 199 kB 4.7 MB/s eta 0:00:01
     |████████████████████████████████| 7.9 MB 57.0 MB/s eta 0:00:01
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 0.24.1
    Uninstalling scikit-learn-0.24.1:
      Successfully uninstalled scikit-learn-0.24.1


In [9]:
smote_oversample = SMOTE(sampling_strategy=0.35)
X, y = smote_oversample.fit_resample(X,y)

In [10]:
counter = Counter(y)
counter

Counter({0: 182838, 1: 63993})

In [11]:
X_train3, X_test3, y_train3, y_test3 = train_test_split(X,y, test_size=0.2, train_size=0.8, random_state=7)

In [13]:
# Training using the Random Forest Regressor
# Importing the model
from sklearn.ensemble import RandomForestClassifier
# Creating the model
modelRF_smote = RandomForestClassifier(n_estimators=100, random_state=7)


# Fitting the model
modelRF_smote.fit(X_train3,y_train3)

RandomForestClassifier(random_state=7)

In [14]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

# Predicting Values for the training set
predsRFTrain = modelRF_smote.predict(X_train3)
print("Training Confusion Matrix:")
confusion_matrix(y_train3, predsRFTrain)
print("Training Accuracy:")
accuracy_score(y_train3, predsRFTrain)


# Predicting the values for the test set
predsRF2 = modelRF_smote.predict(X_test3)

print("\nTest Confusion Matrix:")
confusion_matrix(y_test3, predsRF2)

print("\nTest Accuracy:")
accuracy_score(y_test3, predsRF2)



Training Confusion Matrix:


array([[146257,      0],
       [     2,  51205]])

Training Accuracy:


0.999989871571527


Test Confusion Matrix:


array([[35238,  1343],
       [ 3541,  9245]])


Test Accuracy:


0.9010675147365649

In [15]:
# Predicting the values for the test set
predsRF2 = modelRF_smote.predict(X_test2)

print("\nTest Confusion Matrix:")
confusion_matrix(y_test2, predsRF2)

print("\nTest Accuracy:")
accuracy_score(y_test2, predsRF2)


Test Confusion Matrix:


array([[36295,   253],
       [  365,  2803]])


Test Accuracy:


0.9844395205962333

In [16]:
# Predicting the values for the test set
predsRF2 = modelRF_smote.predict(X_test)

print("\nTest Confusion Matrix:")
confusion_matrix(y_test, predsRF2)

print("\nTest Accuracy:")
accuracy_score(y_test, predsRF2)


Test Confusion Matrix:


array([[18100,   136],
       [  177,  1445]])


Test Accuracy:


0.9842380904421392

In [17]:
# Predicting the values for the test set
predsRF2 = modelRF_smote.predict(X_valid)

print("\nTest Confusion Matrix:")
confusion_matrix(y_valid, predsRF2)

print("\nTest Accuracy:")
accuracy_score(y_valid, predsRF2)


Test Confusion Matrix:


array([[36306,   248],
       [  364,  2797]])


Test Accuracy:


0.9845902052121365

In [24]:
counter = Counter(y_train2)
counter
smote_oversample = SMOTE(sampling_strategy=0.35)
X2, y2 = smote_oversample.fit_resample(X_train2,y_train2)
counter = Counter(y2)
counter
X_train4, X_test4, y_train4, y_test4 = train_test_split(X2,y2, test_size=0.2, train_size=0.8, random_state=7)

Counter({0: 146290, 1: 12570})

Counter({0: 146290, 1: 51201})

In [25]:
# Creating the model
modelRF_smote2 = RandomForestClassifier(n_estimators=100, random_state=7)

# Fitting the model
modelRF_smote2.fit(X_train4,y_train4)

RandomForestClassifier(random_state=7)

In [26]:
# Predicting Values for the training set
predsRFTrain = modelRF_smote2.predict(X_train4)
print("Training Confusion Matrix:")
confusion_matrix(y_train4, predsRFTrain)
print("Training Accuracy:")
accuracy_score(y_train4, predsRFTrain)


# Predicting the values for the test set
predsRF2 = modelRF_smote2.predict(X_test4)

print("\nTest Confusion Matrix:")
confusion_matrix(y_test4, predsRF2)

print("\nTest Accuracy:")
accuracy_score(y_test4, predsRF2)

Training Confusion Matrix:


array([[117049,      0],
       [     0,  40943]])

Training Accuracy:


1.0


Test Confusion Matrix:


array([[28151,  1090],
       [ 2804,  7454]])


Test Accuracy:


0.9014152257019165

In [27]:
# Predicting the values for the test set
predsRF2 = modelRF_smote2.predict(X_test2)

print("\nTest Confusion Matrix:")
confusion_matrix(y_test2, predsRF2)

print("\nTest Accuracy:")
accuracy_score(y_test2, predsRF2)


Test Confusion Matrix:


array([[35241,  1307],
       [ 2376,   792]])


Test Accuracy:


0.9072665928089435

In [28]:
# Predicting the values for the test set
predsRF2 = modelRF_smote2.predict(X_test)

print("\nTest Confusion Matrix:")
confusion_matrix(y_test, predsRF2)

print("\nTest Accuracy:")
accuracy_score(y_test, predsRF2)


Test Confusion Matrix:


array([[17752,   484],
       [  866,   756]])


Test Accuracy:


0.9320173229932521

In [29]:
# Predicting the values for the test set
predsRF2 = modelRF_smote2.predict(X_valid)

print("\nTest Confusion Matrix:")
confusion_matrix(y_valid, predsRF2)

print("\nTest Accuracy:")
accuracy_score(y_valid, predsRF2)


Test Confusion Matrix:


array([[35608,   946],
       [ 1706,  1455]])


Test Accuracy:


0.9332242225859247

In [49]:
from imblearn.under_sampling import RandomUnderSampler
from imblearn.pipeline import Pipeline
from imblearn.over_sampling import SMOTE

counter = Counter(y_train2)
counter
smote_oversample = SMOTE(sampling_strategy=0.5)
#random_undersample = RandomUnderSampler(sampling_strategy=0.9)
#steps = [('o', smote_oversample), ('u', random_undersample)]
#pipeline_sample = Pipeline(steps=steps)
#X3, y3 = pipeline_sample.fit_resample(X_train2,y_train2)
X3, y3 = smote_oversample.fit_resample(X_train2,y_train2)
counter = Counter(y3)
counter
X_train5, X_test5, y_train5, y_test5 = train_test_split(X3,y3, test_size=0.2, train_size=0.8, random_state=7)

Counter({0: 146290, 1: 12570})

Counter({0: 146290, 1: 73145})

In [50]:
# Creating the model
modelRF_smote3 = RandomForestClassifier(n_estimators=100, random_state=7, max_depth=20)

# Fitting the model
modelRF_smote3.fit(X_train5,y_train5)

RandomForestClassifier(max_depth=20, random_state=7)

In [51]:
# Predicting Values for the training set
predsRFTrain = modelRF_smote3.predict(X_train5)
print("Training Confusion Matrix:")
confusion_matrix(y_train5, predsRFTrain)
print("Training Accuracy:")
accuracy_score(y_train5, predsRFTrain)


# Predicting the values for the test set
predsRF2 = modelRF_smote3.predict(X_test5)

print("\nTest Confusion Matrix:")
confusion_matrix(y_test5, predsRF2)

print("\nTest Accuracy:")
accuracy_score(y_test5, predsRF2)

Training Confusion Matrix:


array([[114956,   2105],
       [  2080,  56407]])

Training Accuracy:


0.9761603663955157


Test Confusion Matrix:


array([[27461,  1768],
       [ 2830, 11828]])


Test Accuracy:


0.8952309339895641

In [52]:
# Predicting the values for the test set
predsRF2 = modelRF_smote3.predict(X_test2)

print("\nTest Confusion Matrix:")
confusion_matrix(y_test2, predsRF2)

print("\nTest Accuracy:")
accuracy_score(y_test2, predsRF2)


Test Confusion Matrix:


array([[34312,  2236],
       [ 2117,  1051]])


Test Accuracy:


0.8903968174035654